num_1=int(input("Enter num 1 : "))
num_2=int(input("Enter num 2 : "))
sum=(num_1+num_2)
difference=(num_1-num_2)
product=(num_1*num_2)
division=(num_1/num_2)
print(f"The sum of {num_1} and {num_2} is {sum}")
print(f"The differnce between {num_1} and {num_2} is {difference}")
print(f"The product of {num_1} and {num_2} is {product}")
print(f"The Division of {num_1} by {num_2} is {division}")